version: '3'
services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - 9090:9090
        command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus-data:/prometheus
        networks:
            - devops-project-network
        depends_on: 
            - backend
    grafana:
        image: grafana/grafana:6.7.2
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
        networks:
            - devops-project-network
        depends_on:
            - prometheus
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        restart: unless-stopped
        depends_on: 
            - database
        env_file: 
            - .env
        networks:
            - devops-project-network
        volumes:
            - backend-logs-volume:/logs
    database:
        image: 'mongo'
        container_name: 'mongo_database'
        env_file: 
            - .env
        volumes:
            - ./scripts/initmongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - mongo-volume:/data/db
        networks:
            - devops-project-network
        restart: unless-stopped
volumes:
    mongo-volume:
    prometheus-data:
    backend-logs-volume:
    grafana_data:
networks:
    devops-project-network:
