# Start from golang v1.13.4 base image to have access to go modules
FROM golang:1.13.4

# create a working directory
WORKDIR /app

# Fetch dependencies on separate layer as they are less likely to
# change on every build and will therefore be cached for speeding
# up the next build
COPY ./app/go.mod ./app/go.sum ./
RUN go mod download

# copy source from the host to the working directory inside
# the container
COPY ./app .

# This container exposes port 7777 to the outside world
EXPOSE 8000

ENTRYPOINT [ "./entry.sh" ]