{
 "title": "Application Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Heatmap Buys",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(product_request_duration_milliseconds_bucket{code=\"200\",path=\"/api/products/buy\",service=\"Product Service\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Histogram Buckets",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(product_request_duration_milliseconds_bucket{code=\"200\",path=\"/api/products\",service=\"Product Service\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Error Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(product_requests_total{service=\"Product Service\",code=\"500\"}[1m]))",
     "legendFormat": " 500 Internal Error Request"
    },
    {
     "expr": "rate(product_requests_total{service=\"Product Service\",code=\"404\"}[1m])",
     "legendFormat": "404 Not Found Error {{method}}"
    }
   ]
  },
  {
   "title": "Total Buy Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(product_requests_total{service=\"Product Service\", path=\"/api/products/buy\",code=\"200\"}[1m])",
     "legendFormat": "Buy Product"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(product_requests_total{service=\"Product Service\", path=\"/api/products\",method=\"GET\",code=\"200\"}[1m])",
     "legendFormat": "GET Product API"
    },
    {
     "expr": "rate(product_requests_total{service=\"Product Service\", path=\"/api/products\", method=\"POST\", code=\"200\"}[1m])",
     "legendFormat": "New Product API"
    },
    {
     "expr": "rate(product_requests_total{service=\"Product Service\", method=\"PUT\",code=\"200\"}[1m])",
     "legendFormat": "Update Product"
    },
    {
     "expr": "rate(product_requests_total{service=\"Product Service\", method=\"DELETE\",code=\"200\"}[1m])",
     "legendFormat": "Delete Product"
    }
   ]
  }
 ]
}