apiVersion: v1
kind: Service
metadata:
  name: backend
  labels: 
    app: backend
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - name: backend
        image: samy30/go-restapi:#{Build.BuildId}#
        ports:
        - containerPort: 8000 
        env:
        - name: PORT
          value: "8000"